# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: confinicky 0.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "confinicky"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Jim Jeffers"]
  s.date = "2014-08-24"
  s.description = "A simple CLI to manage environment variables on your local machine. Perform basic CRUD for your environment variables all in the command line."
  s.email = "jim@sumocreations.com"
  s.executables = ["cfy"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "bin/cfy",
    "confinicky.gemspec",
    "lib/confinicky.rb",
    "lib/confinicky/commands.rb",
    "lib/confinicky/commands/clean.rb",
    "lib/confinicky/commands/duplicates.rb",
    "lib/confinicky/commands/inspect.rb",
    "lib/confinicky/commands/list.rb",
    "lib/confinicky/commands/remove.rb",
    "lib/confinicky/commands/set.rb",
    "lib/confinicky/commands/setup.rb",
    "lib/confinicky/config.rb",
    "lib/confinicky/configuration_file.rb",
    "lib/confinicky/controllers/aliases.rb",
    "lib/confinicky/controllers/commands.rb",
    "lib/confinicky/controllers/exports.rb",
    "lib/confinicky/parsers/command.rb",
    "lib/confinicky/parsers/expression.rb",
    "lib/confinicky/shell_file.rb",
    "lib/confinicky/version.rb",
    "test/helper.rb",
    "test/sample_bash_file.sh",
    "test/test_command_parser.rb",
    "test/test_controllers.rb",
    "test/test_shell_file_parsing.rb"
  ]
  s.homepage = "http://github.com/jimjeffers/confinicky"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "A simple CLI to manage environment variables on your local machine."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<commander>, ["~> 4.1"])
      s.add_runtime_dependency(%q<terminal-table>, ["~> 1.4"])
      s.add_development_dependency(%q<minitest>, ["~> 5.4"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.9"])
    else
      s.add_dependency(%q<commander>, ["~> 4.1"])
      s.add_dependency(%q<terminal-table>, ["~> 1.4"])
      s.add_dependency(%q<minitest>, ["~> 5.4"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<simplecov>, ["~> 0.9"])
    end
  else
    s.add_dependency(%q<commander>, ["~> 4.1"])
    s.add_dependency(%q<terminal-table>, ["~> 1.4"])
    s.add_dependency(%q<minitest>, ["~> 5.4"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<simplecov>, ["~> 0.9"])
  end
end

